### ISSUE TITLE
FR: Play the  whole library

### ISSUE THREAD

**Issue by gerroon** [smithdtyler/prettygoodmusicplayer#100]
Hi

While browsing the folders is neat, it would be nice if there is a top level play everything in the music folder. We could have "Play all", "Play Random" etc.

**Comment by smithdtyler** [comment]
This is a good idea, but I'm not sure exactly how to add it from a UI perspective. I'm hesitant to add another menu option - perhaps an initial item before the list of artists?

**Comment by gerroon** [comment]
Maybe you do not have to add a ui thing, but it can be like a fake folder at the top of the folder list?

**Comment by smithdtyler** [comment]
This is a good ideal. I'll implement it when I have time, otherwise feel free to take a stab at it!

**Comment by gerroon** [comment]
I am not a dev. But thanks for considering it. I use it on my Eink Android device and it is the ideal player because it is small and not resource hungry.

**Comment by notpokey** [comment]
Perhaps if PGMP played the last track in a folder, it could just begin playing the first track in the next folder. No option or extra button is really needed for that.

**Comment by smithdtyler** [comment]
That's a good idea. I'm working on something along these lines, if you're
curious the source is here:
https://github.com/smithdtyler/prettygoodmusicplayer/tree/playall

**Comment by notpokey** [comment]
I used to have a music player that would play every file in the directory
that it started in, and then would play files in sub-directories. What it
wouldn't do is, it wouldn't play anything in a directory that was higher
than the one that it started in. For example (Assuming: Music > Artist >
Album) if I started in an Artist folder it could play all the albums by
that artist, IF there was a track outside of the Album folders, but it
wouldn't play any other artists. My solution to this was to place an empty
file called PlayAll.ogg in  the Music folder, and in each Artist  folder. I
know its not elegant, but it worked while I needed it.

Perhaps something in there may spark some inspiration...

**Comment by smithdtyler** [comment]
I implemented something like this in 3.3.2, hopefully it will get close to what you're looking for. I'm going to close this issue, but feel free to re-open it or make a new one if 3.3.2 doesn't cut it.

**Comment by notpokey** [comment]
I saw it, and I tried it. It appears to work very well.

I reverted to 3.2.11 though because I still have the "pause button skips to
the next track" bug on any later version.

OH! I forgot to tell you: I don't think its related to Bluetooth. I just
only ever used PGMP with Bluetooth up until recently.

**Comment by smithdtyler** [comment]
Is there an open issue for that problem? I haven't encountered it before,
and I'm not able to replicate it on my phone (running 3.3.2).

**Comment by notpokey** [comment]
Yes, but I reported it as a Bluetooth problem.
